name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - lib/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - name: Download dependencies
        run: flutter pub get

      - name: Run Flutter Format
        run: flutter format --set-exit-if-changed lib

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Run unit tests
        run: flutter test
